namespace GroundNotes.Models;

public sealed record SettingsDialogModel(
    IReadOnlyList<string> ThemeNames,
    IReadOnlyList<BundledFontFamilyOption> FontFamilies,
    string SelectedThemeName,
    string SelectedUiFontFamilyName,
    string SelectedUiFontVariantName,
    string SelectedFontFamilyName,
    string SelectedFontVariantName,
    string SelectedCodeFontFamilyName,
    string SelectedCodeFontVariantName,
    double EditorFontSize,
    double UiFontSize,
    double FileListFontSize,
    bool ShowSidebarListBackground,
    bool ShowSidebarListBorder,
    int EditorIndentSize,
    double EditorLineHeightFactor,
    bool ShowScrollBars,
    bool IsAiEnabled,
    string ApiKey,
    string DefaultModel,
    string DefaultReasoningEffort,
    string ProjectId,
    string OrganizationId,
    bool IsTitleGenerationEnabled,
    string TitleGenerationModel,
    string TitleGenerationReasoningEffort,
    string PromptsDirectory,
    IReadOnlyList<AiPromptDefinition> AiPrompts,
    KeyboardShortcutSettings KeyboardShortcuts,
    VimModeSettings? VimModeSettings = null);
